# Generated by Django 3.1.7 on 2021-03-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210330_0541'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_type',
            field=models.CharField(choices=[('Each', 'each'), ('KG', 'kg')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
